name: yuro_plugin
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/YuroLtd/yuro_kit.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  json_serializable: ^6.1.0



flutter:
  plugin:
    platforms:
      android:
        package: com.yuro.plugin
        pluginClass: YuroPlugin
      ios:
        pluginClass: YuroPlugin