name: yuro_plugin
description: A new Flutter project.
version: 0.1.0+2
homepage: https://github.com/YuroLtd/yuro_plugin

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  json_annotation: ^4.7.0
  collection: ^1.16.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.2

flutter:

  plugin:
    platforms:
      android:
        package: com.yuro.yuro_plugin
        pluginClass: YuroPlugin
      ios:
        pluginClass: YuroPlugin
